import { createSlice } from '@reduxjs/toolkit';

// ── cartSlice ──────────────────────────────────────────────────────────────
// Manages the global shopping cart state.
// Redux Toolkit uses Immer under the hood, so direct "mutations" inside
// reducers are safe — Immer converts them into pure immutable updates.

const cartSlice = createSlice({
  name: 'cart', // Action types will be prefixed: 'cart/addItem', 'cart/removeItem', etc.
  initialState: {
    items: [],           // [{ id, name, price, quantity }]
    totalQuantity: 0,
    totalPrice: 0,
  },
  reducers: {
    // addItem — adds a product, or increments quantity if it already exists
    addItem: (state, action) => {
      const product = action.payload;
      const existing = state.items.find(item => item.id === product.id);

      if (existing) {
        existing.quantity += 1;
      } else {
        state.items.push({ ...product, quantity: 1 });
      }

      state.totalQuantity += 1;
      state.totalPrice += product.price;
    },

    // removeItem — removes the entire item from the cart by id
    removeItem: (state, action) => {
      const id = action.payload;
      const item = state.items.find(i => i.id === id);
      if (!item) return;

      state.totalQuantity -= item.quantity;
      state.totalPrice -= item.price * item.quantity;
      state.items = state.items.filter(i => i.id !== id);
    },

    // updateQuantity — adjusts the quantity of a specific item
    updateQuantity: (state, action) => {
      const { id, quantity } = action.payload;
      if (quantity < 1) return;

      const item = state.items.find(i => i.id === id);
      if (!item) return;

      const diff = quantity - item.quantity;
      state.totalQuantity += diff;
      state.totalPrice += diff * item.price;
      item.quantity = quantity;
    },

    // clearCart — resets cart to its initial empty state
    clearCart: (state) => {
      state.items = [];
      state.totalQuantity = 0;
      state.totalPrice = 0;
    },
  },
});

// Export individual action creators (auto-generated by createSlice)
export const { addItem, removeItem, updateQuantity, clearCart } = cartSlice.actions;

// Export the reducer to be registered in the store
export default cartSlice.reducer;
